services:
    backend:
        image: funcalls
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
        expose:
            - "9000"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www/app
            - ./docker/backend/99-php.ini:/usr/local/etc/php/conf.d/99-php.ini
        networks:
            - app-network
        depends_on:
            - redis

    nginx:
        image: nginx:1.29.1
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
        networks:
            - app-network
        depends_on:
            - backend

    pgsql:
        image: 'postgres:17'
        ports:
          - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
          - 'vol-pgsql:/var/lib/postgresql/data'
        networks:
          - app-network

    redis:
        image: 'redis:7.4'
        expose:
            - "6379"
        volumes:
            - 'vol-redis:/data'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    vol-redis:
        driver: local
    vol-pgsql:
        driver: local
